package com.ljarocki.shadedjar;

import org.apache.logging.log4j.core.config.plugins.processor.PluginCache;
import org.apache.logging.log4j.core.config.plugins.processor.PluginEntry;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

/**
 * Merges every source's {@code Log4j2Plugins.dat} — log4j2's binary
 * plugin-discovery cache, generated by its own annotation processor — into
 * one unified cache, instead of first-wins silently discarding every source
 * but one (log4j2's plugin discovery would then be missing every plugin from
 * the sources that got dropped).
 *
 * <p>Reuses log4j-core's own {@link PluginCache}/{@link PluginEntry} directly
 * (an {@code implementation} dependency of this plugin — build-time only,
 * never bundled into a consuming project's jar) rather than hand-rolling the
 * binary format ourselves: {@code writeCache}'s framing is nontrivial enough
 * that a subtle mismatch would silently break plugin discovery at runtime,
 * and this guarantees exact fidelity with whatever log4j2 version a project
 * actually bundles.
 *
 * <p>Unlike service files and the Spring properties files (which relocate
 * their content per-source in {@link SourcePacker}, then merge in {@code
 * FatJarTask.assemble}), a plugin cache's entries are relocated once, after
 * merging — {@code PluginEntry}'s class name is a plain string rewrite
 * unaffected by merge order, and {@link PluginCache#loadCacheFiles} needs a
 * real decode step regardless of whether relocation is even active, so
 * there's no per-source work worth doing separately.
 */
final class Log4j2PluginCacheMerger {

    /** Where log4j2's own annotation processor writes the cache; the exact, fixed path it (and this) always uses. */
    static final String ENTRY_NAME = "META-INF/org/apache/logging/log4j/core/config/plugins/Log4j2Plugins.dat";

    private Log4j2PluginCacheMerger() {
    }

    /**
     * @param sourceCaches each source's raw {@code Log4j2Plugins.dat} bytes, in
     *     classpath order.
     * @param tempDir scratch directory this may write temp files into — {@link
     *     PluginCache#loadCacheFiles} reads from {@link URL}s, not streams/bytes
     *     directly, so each source's bytes are staged to a temp file first.
     * @param relocator applied to each merged entry's declared class name (not
     *     its lookup key or category, which aren't class names); a no-op when
     *     {@link Relocator#isEmpty()}.
     * @return the merged cache's own bytes, ready to write as the single output entry.
     */
    static byte[] merge(List<byte[]> sourceCaches, File tempDir, Relocator relocator) throws IOException {
        tempDir.mkdirs();
        List<URL> urls = new ArrayList<>(sourceCaches.size());
        for (int i = 0; i < sourceCaches.size(); i++) {
            File f = new File(tempDir, "log4j2-plugins-" + i + ".dat");
            Files.write(f.toPath(), sourceCaches.get(i));
            urls.add(f.toURI().toURL());
        }

        PluginCache cache = new PluginCache();
        cache.loadCacheFiles(Collections.enumeration(urls));

        if (!relocator.isEmpty()) {
            for (Map<String, PluginEntry> category : cache.getAllCategories().values()) {
                for (PluginEntry entry : category.values()) {
                    entry.setClassName(relocator.relocateDottedName(entry.getClassName()));
                }
            }
        }

        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        cache.writeCache(bos);
        return bos.toByteArray();
    }
}
